---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-sqldb-postgres-query
  annotations:
    version: v0.1.0
    description: |
      Demo WebAssembly component using the wasmCloud SQLDB Postgres provider via the wasmcloud:postgres WIT interface
spec:
  components:
    - name: querier
      type: component
      properties:
        image: ghcr.io/joriatyben/sqldb-postgres-query-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: default-postgres

    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.2.0
        config:
          - name: 'default-postgres'
